Feature/vancouver
real-account-book/real-account-book pull request #23
Opened 2024-07-21 09:37 UTC by brrkak

- [ ] total, plus ,minus, category Controller 예외처리
- [ ] router : validator 기능 추가 
- [ ] router : export default로 설정
- [ ] update 부분: uploaded_at = req.body 추가
- [ ] 폴더명 수정 : useSearchMinus -> useSearch

2024-07-21 10:29 UTC, paengjiwoo commented
주말에도 열심히 하시는군요 👍

2024-07-22 06:01 UTC, rhkdgns95 requested changes
리뷰 다시 작성하여 전달드립니다.

2024-07-22 06:01 UTC, rhkdgns95 commented on server/routes/total.ts
> +totalRouter.get("/minus/:start_at/:end_at/:categoryId?",
@brrkak  다음과 같이 수정이 필요할걸까요?

Before
```
totalRouter.get("/minus/:start_at/:end_at/:categoryId?", 
```

After
```
totalRouter.get("/minus/:start_at/:end_at/:categoryId", 
```

2024-07-22 06:01 UTC, rhkdgns95 commented on server/routes/total.ts
> +totalRouter.get("/minus/:start_at/:end_at/:categoryId?",
@brrkak 보이시나요?

2024-07-22 06:09 UTC, brrkak commented on server/routes/total.ts
> +totalRouter.get("/minus/:start_at/:end_at/:categoryId?",
보입니당!

2024-07-22 06:10 UTC, rhkdgns95 approved these changes

2024-07-22 06:11 UTC, brrkak reviewed
리뷰해결

2024-07-22 06:11 UTC, merged